# Generated by Django 3.1.6 on 2021-02-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('current_value', models.FloatField()),
                ('historical_values', models.JSONField(default=list)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_owned', models.FloatField()),
                ('value_purchased_at', models.FloatField()),
                ('platform', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
            options={
                'verbose_name_plural': 'Owned',
            },
        ),
    ]
